refactor all messages, prompts, and methods to avoid code duplication

diff --git a/kebab b/kebab
--- a/kebab
+++ b/kebab
@@ -10,14 +10,12 @@ usage() {
         
 }
 
-#get_absolute_path(){
-    # function that sets the path to absolute path to avoid issues with renaming dots (.) when used recursively
-#}
 set_rename_pattern(){
     # Still an issue with unable to find and substitute first character of the string (in this case either - or _) in recursive FIND mode ONLY. In targeted mode this works fine.
     # Still needs a way to rename dots (.) in the filename without removing the file extension: idea:
     # s/\.(?![^.]+$)/_/g;
-    pattern=$'s/_+|\s+/-/g; s/--+/-/g; s/^-//g; s/-\.$/\./g; y/A-Z/a-z/; y/ÆØÅ/æøå/'
+    recursive_pattern=$'s/_+|\s+/-/g; s/--+/-/g; s/^-//g; s/-\.$/\./g; y/A-Z/a-z/; y/ÆØÅ/æøå/'
+    selective_pattern=$'s/\.(?![^.]+$)/_/g; s/_+|\s+/-/g; s/--+/-/g; s/^-|-$//g; s/-\.$/\./g; y/A-Z/a-z/; y/ÆØÅ/æøå/'
     # reg ex pattern explained:
     # s/_+|\s+/-/g = find one or more underscores _ OR (|) one or more whitespace (\s) and replace with a dash -
     # s/--+/-/g = replace any dash trailed by one or more dashes (-+) with a single dash
@@ -26,21 +24,11 @@ set_rename_pattern(){
     # y/ÆØÅ/æøå/ = replace all lower case DK chars to upper case (needs to be part of separate pattern for some reason.
 }
 
-#dry_run_rename(){
-#    # function that runs a dry run 
-#}
-#
-#rename_files(){
-#    # function that simply calls perl-rename with an argument array and exits
-#}
-
 check_selected_files(){
     # function that checks the selected files
     # we first need to check all arguments to make sure that the selected files are valid
     if [[ $# -eq 0 ]]; then
-        echo "Illegal number of parameters: $#" >&2
-        usage
-        exit 2
+        msg_illegal_parameters "$@"
     else 
         arg_arr=("$@")
 
@@ -48,90 +36,105 @@ check_selected_files(){
         for i in "${arg_arr[@]}"
             do
                 if [[ ! -e $i ]]; then
-                   echo -e "$i is not a valid path.\nExiting." >&2
-                   exit 2
+                   msg_invalid_path "$1"
                 fi
             done
     fi
 }
-
-#check_recursive_path(){
-#    # function that checks the path for performing the recursive operation
-#}
 
 rename_selected_files(){
     # we first need to check all arguments to make sure that the selected files are valid
     # sending the argument array $@ to the checker
     check_selected_files "$@"
 
-#    if [[ $# -eq 0 ]]; then
-#        echo "Illegal number of parameters: $#" >&2
-#        usage
-#        exit 2
-#    else 
-#        arg_arr=("$@")
-#
-#        ## now loop through the above array
-#        for i in "${arg_arr[@]}"
-#            do
-#                if [[ ! -e $i ]]; then
-#                   echo -e "$i is not a valid path.\nExiting." >&2
-#                   exit 2
-#                fi
-#            done
-#    fi
     # perform the rename on all elements in arg_arr
     set_rename_pattern
     
-    count_var=$(perl-rename -fnv -- "$pattern" "${arg_arr[@]}" | wc -l)
-    echo "The following $count_var elements will be renamed: "
-    # the following needs to also be added 
-    perl-rename -fnv -- "$pattern" "${arg_arr[@]}"
+    count_var=$(perl-rename -fnv -- "$selective_pattern" "${arg_arr[@]}" | wc -l)
+    msg_show_renamed
+    # run a dry run
+    perl-rename -fnv -- "$selective_pattern" "${arg_arr[@]}"
+    prompt_proceed    
 
-    read -p "Do you want to proceed with the rename? (y/n) " -n 1 -r
-    echo -e "\n"
-
-    if [[ $REPLY =~ ^[Yy]$ ]]
+    if [[ "$response" =~ ^(yes|y)$ ]]
         then
-            perl-rename -fv -- "$pattern" "${arg_arr[@]}"
-
+           perl-rename -fv -- "$selective_pattern" "${arg_arr[@]}"
+           msg_rename_complete
         else
-            echo "Aborting."
+            msg_aborting
     fi
     }
 
+check_parameters(){
+    if [[ $# -ne 1 ]]; then
+        msg_illegal_parameters "$@"
+    fi
+}
+check_recursive_path(){
+    if [[ ! -d $1 ]]; then
+        msg_invalid_path "$1"
+        msg_exit_fail
+    fi 
+}
+
 rename_recursively(){
     # check that only one argument is provided
-    if [[ $# -ne 1 ]]; then
-        echo "Illegal number of parameters: $#" >&2
-        usage
-        exit 2
-    fi
-    arg=$1
-    if [[ ! -d $arg ]]; then
-        echo "$arg is not a valid path."
-        echo "Exiting..." >&2
-        exit_fail
-    else
-       set_rename_pattern
-       # The following command is an alternative to find -execdir using xargs which also works
-       #find $arg -depth -print0 | xargs -0 perl-rename -fnv -- "$pattern"
-       find $arg -depth -execdir perl-rename -fnv -- "$pattern" {} +
-       read -p "Do you want to proceed with the rename? (y/n) " -n 1 -r
-       echo    # (optional) move to a new line
-
-       if [[ $REPLY =~ ^[Yy]$ ]]
-       then
-           find $arg -depth -execdir perl-rename -fv -- "$pattern" {} +
-           echo
-           echo "Files renamed to kebab-case."
-       fi
+    check_parameters "$@"
+    # check that the path is a valid directory
+    check_recursive_path "$1"
+    # set argument to absolute path to avoid dot replacement issues
+    path="$(realpath $1)"
+    set_rename_pattern
+    # The following command is an alternative to find -execdir using xargs which also works
+    #find $path -depth -print0 | xargs -0 perl-rename -fnv -- "$recursive_pattern"
+    # dry run to check that all elements will be renamed correctly
+    count_var=$(find $path -depth -execdir perl-rename -fnv -- "$recursive_pattern" {} + | wc -l) 
+    msg_show_renamed
+    find $path -depth -execdir perl-rename -fnv -- "$recursive_pattern" {} +
+    prompt_proceed
+    if [[ "$response" =~ ^(yes|y)$ ]]
+        then
+           find $path -depth -execdir perl-rename -fv -- "$recursive_pattern" {} +
+           msg_rename_complete
+        else
+            msg_aborting
     fi
 }
 
-# function to call so save 
-exit_fail() {
+prompt_proceed(){
+    #read -p "Do you want to proceed with the rename? (y/n) " -n 1 -r
+    read -r -p "Do you want to proceed with the rename? (y/n) " response
+    response=${response,,}    # tolower
+    echo    # (optional) move to a new line
+}
+msg_show_renamed(){
+    echo "The following $count_var elements will be renamed: "
+}
+
+msg_rename_complete(){
+   echo
+   echo "Files renamed to kebab-case."
+}
+
+msg_invalid_path(){
+    echo "$1 is not a valid path."
+    echo "Exiting..." >&2
+    echo
+    msg_exit_fail
+}
+
+msg_illegal_parameters(){
+    echo "Illegal number of parameters: $#" >&2
+    msg_exit_fail
+}
+
+msg_aborting(){
+    echo "Aborting."
+    exit 2
+}
+msg_exit_fail() {
     usage
+    echo
     exit 2
 }
 
